# Generated by Django 5.2.7 on 2025-10-14 23:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
                ('author', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Book',
                'verbose_name_plural': 'Books',
                'db_table': 'books',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Friend',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
            options={
                'verbose_name': 'Friend',
                'verbose_name_plural': 'Friends',
                'db_table': 'friends_relationships',
                'ordering': ['user'],
            },
        ),
        migrations.CreateModel(
            name='GoodreadsAccount',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='goodreads_account', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('friends', models.ManyToManyField(blank=True, related_name='friends_of', through='goodreads.Friend', to='goodreads.goodreadsaccount')),
            ],
            options={
                'db_table': 'goodreads_accounts',
            },
        ),
        migrations.AddField(
            model_name='friend',
            name='friend',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_to', to='goodreads.goodreadsaccount'),
        ),
        migrations.AddField(
            model_name='friend',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friendship_from', to='goodreads.goodreadsaccount'),
        ),
        migrations.CreateModel(
            name='UserBook',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='book_users', to='goodreads.book')),
                ('goodreads_account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='goodreads_account_user_books', to='goodreads.goodreadsaccount')),
            ],
            options={
                'verbose_name': 'UserBook',
                'verbose_name_plural': 'UserBooks',
                'db_table': 'user_books',
                'ordering': ['goodreads_account', 'book'],
                'unique_together': {('goodreads_account', 'book')},
            },
        ),
        migrations.AddField(
            model_name='goodreadsaccount',
            name='user_books',
            field=models.ManyToManyField(blank=True, related_name='user_owned_books', through='goodreads.UserBook', to='goodreads.book'),
        ),
    ]
