# Generated by Django 5.2.7 on 2025-10-15 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('goodreads', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='goodreadsaccount',
            name='friends',
            field=models.ManyToManyField(blank=True, through='goodreads.Friend', to='goodreads.goodreadsaccount'),
        ),
    ]
