# Generated by Django 5.2.7 on 2025-10-10 06:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Climate',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Climate',
                'verbose_name_plural': 'Climates',
                'db_table': 'climates',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Terrain',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Terrain',
                'verbose_name_plural': 'Terrains',
                'db_table': 'terrains',
                'ordering': ['name'],
            },
        ),
        migrations.RemoveField(
            model_name='planet',
            name='climates',
        ),
        migrations.RemoveField(
            model_name='planet',
            name='terrains',
        ),
        migrations.AddField(
            model_name='planet',
            name='climates',
            field=models.ManyToManyField(related_name='planets', to='planets.climate'),
        ),
        migrations.AddField(
            model_name='planet',
            name='terrains',
            field=models.ManyToManyField(related_name='planets', to='planets.terrain'),
        ),
    ]
