# Generated by Django 5.2.7 on 2025-10-12 03:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0002_climate_terrain_remove_planet_climates_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='population',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
