# Generated by Django 5.2.7 on 2025-10-12 03:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planets', '0003_alter_planet_population'),
    ]

    operations = [
        migrations.AlterField(
            model_name='planet',
            name='climates',
            field=models.ManyToManyField(blank=True, related_name='planets', to='planets.climate'),
        ),
        migrations.AlterField(
            model_name='planet',
            name='terrains',
            field=models.ManyToManyField(blank=True, related_name='planets', to='planets.terrain'),
        ),
    ]
